### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by aliciahurst** [contentauth/c2pa-js-legacy#43]
Congrats on the launch of this tool! Excited to take a look. 

The examples throughout the pages that use codesandbox.io don't seem to be working on any browser. The images are 404ing, and it's possible scripts aren't loading either. 
https://js-sdk.contentauthenticity.org/docs/getting-started/quick-start
https://js-sdk.contentauthenticity.org/docs/guides/viewing-provenance

I also found that the Lucidchart diagram at the bottom of the page here doesn't load either
https://js-sdk.contentauthenticity.org/docs/getting-started/quick-start 

Thanks for looking into this!

**Comment by dkozma** [comment]
Hi @aliciahurst - apologies but we still had our old website on the README - the correct site is at https://opensource.contentauthenticity.org/ - please let me know if this solves your issues and we will update the README shortly.

**Comment by aliciahurst** [comment]
@dkozma oh, haha, perfect! thank you so much, yes everything works as expected there.
