### ISSUE TITLE
JS should support all assertions included in manifest

### ISSUE THREAD

**Issue by andrewjenks** [contentauth/c2pa-js-legacy#44]
There seems to be a very limited number of assertions supported in the JS.  Is there a way to access additional assertions that are included in the manifest but not exposed by autocomplete?

**Comment by emensch** [comment]
Hi @andrewjenks - though we are currently only shipping TypeScript type definitions for a small subset of c2pa assertions, you should be able to access any assertion on the manifest as long as you know the label, albeit without type information. 

i.e.
```javascript
activeManifest.assertions.get('some.assertion.label') 
```

should work, you'll just have to deal with an `any` return type.

We'll provide guidance on extending the TS definitions with custom assertion types soon :)
