### ISSUE TITLE
Allow `selectEditsAndActivity` to work without a `Manifest` object

### ISSUE THREAD

**Issue by dkozma** [contentauth/c2pa-js-legacy#75]
This is a request from @DaveStein - he wants to use the logic from `selectEditsAndActivity` together with a web component but he doesn't have a `Manifest` object available. A possible option would be to allow a new exported function to take an `actions` assertion as input, since that is the main part of the manifest that is needed.

**Comment by dkozma** [comment]
@adobe export issue to Jira project CAI

**Comment by dkozma** [comment]
Actually on second thought, we may be able to easily support this just by exporting [`getC2paCategorizedActions`](https://github.com/contentauth/c2pa-js/blob/47a7f3a7cb378b2af05591b4f0b614ea6fef2dd3/packages/c2pa/src/selectors/selectEditsAndActivity.ts#L188). @emensch do you see any issues with that?

**Comment by emensch** [comment]
That makes sense to me - do we want to provide support for the "legacy" photoshop-specific actions as well?

**Comment by dkozma** [comment]
It sounds like those aren't needed @emensch - we can expose that later if it turns out that is not the case, but I don't want to make that part of the API unless we need to since they are non-standard.

**Comment by dkozma** [comment]
Closed by #76.
